USE [NODE_TEST]
GO

/****** Object:  Table [nodetest].[EMPRESA] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[nodetest].[EMPRESA]') AND type in (N'U'))
BEGIN
CREATE TABLE [nodetest].[EMPRESA](
	[ID_EMPRESA] [int] IDENTITY(1,1) NOT NULL,
	[EMPRESA] [varchar](200) NOT NULL,
	[CNPJ] [numeric](14, 0) NOT NULL,
	[PROPRIETARIO] [bit] NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[DETALHES] [varchar](max) NULL,
	[DATA_LIMITE_USO] [datetime] NULL,
	[DATA_CRIACAO] [datetime] NOT NULL,
 CONSTRAINT [PK_EMPRESA] PRIMARY KEY CLUSTERED
(
	[ID_EMPRESA] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

/****** Object:  Table [nodetest].[FUNCAO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[nodetest].[FUNCAO]') AND type in (N'U'))
BEGIN
CREATE TABLE [nodetest].[FUNCAO](
	[ID_FUNCAO] [int] NOT NULL,
	[FUNCAO] [varchar](50) NOT NULL,
	[DESCRICAO] [varchar](200) NOT NULL,
 CONSTRAINT [PK_FUNCAO] PRIMARY KEY CLUSTERED
(
	[ID_FUNCAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

/****** Object:  Table [nodetest].[LOGS] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[nodetest].[LOGS]') AND type in (N'U'))
BEGIN
CREATE TABLE [nodetest].[LOGS](
	[ID_LOGS] [int] IDENTITY(1,1) NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
	[IP] [varchar](20) NOT NULL,
	[DATA_INSERCAO] [datetime] NOT NULL,
 CONSTRAINT [PK_LOGS] PRIMARY KEY CLUSTERED
(
	[ID_LOGS] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

/****** Object:  Table [nodetest].[PERFIL] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[nodetest].[PERFIL]') AND type in (N'U'))
BEGIN
CREATE TABLE [nodetest].[PERFIL](
	[ID_PERFIL] [int] NOT NULL,
	[PERFIL] [varchar](50) NOT NULL,
 CONSTRAINT [PK_PERFIL] PRIMARY KEY CLUSTERED
(
	[ID_PERFIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

/****** Object:  Table [nodetest].[PERFIL_FUNCAO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[nodetest].[PERFIL_FUNCAO]') AND type in (N'U'))
BEGIN
CREATE TABLE [nodetest].[PERFIL_FUNCAO](
	[ID_PERFIL] [int] NOT NULL,
	[ID_FUNCAO] [int] NOT NULL,
 CONSTRAINT [PK_PERFIL_FUNCAO] PRIMARY KEY CLUSTERED
(
	[ID_PERFIL] ASC,
	[ID_FUNCAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

/****** Object:  Table [nodetest].[PERFIL_USUARIO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[nodetest].[PERFIL_USUARIO]') AND type in (N'U'))
BEGIN
CREATE TABLE [nodetest].[PERFIL_USUARIO](
	[ID_PERFIL] [int] NOT NULL,
	[ID_USUARIO] [int] NOT NULL,
 CONSTRAINT [PK_PERFIL_USUARIO] PRIMARY KEY CLUSTERED
(
	[ID_PERFIL] ASC,
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

/****** Object:  Table [nodetest].[USUARIO] ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF NOT EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[nodetest].[USUARIO]') AND type in (N'U'))
BEGIN
CREATE TABLE [nodetest].[USUARIO](
	[ID_USUARIO] [int] IDENTITY(1,1) NOT NULL,
	[ID_EMPRESA] [int] NOT NULL,
	[NOME] [varchar](200) NOT NULL,
	[EMAIL] [varchar](200) NOT NULL,
	[CPF] [numeric](11, 0) NOT NULL,
	[SENHA] [varchar](128) NOT NULL,
	[SALT] [varchar](5) NOT NULL,
	[ATIVO] [bit] NOT NULL,
	[DELETADO] [datetime] NULL,
	[DETALHES] [varchar](max) NULL,
	[DATA_CRIACAO] [datetime] NOT NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED
(
	[ID_USUARIO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
END
GO

SET ANSI_PADDING ON
GO

/****** Object:  Index [UK_EMPRESA_CNPJ] ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[nodetest].[EMPRESA]') AND name = N'UK_EMPRESA_CNPJ')
CREATE UNIQUE NONCLUSTERED INDEX [UK_EMPRESA_CNPJ] ON [nodetest].[EMPRESA]
(
	[CNPJ] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [UK_EMPRESA_PROPRIETARIO] ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[nodetest].[EMPRESA]') AND name = N'UK_EMPRESA_PROPRIETARIO')
CREATE UNIQUE NONCLUSTERED INDEX [UK_EMPRESA_PROPRIETARIO] ON [nodetest].[EMPRESA]
(
	[PROPRIETARIO] ASC
)
WHERE ([PROPRIETARIO]=(1))
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [UK_FUNCAO_FUNCAO] ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[nodetest].[FUNCAO]') AND name = N'UK_FUNCAO_FUNCAO')
CREATE UNIQUE NONCLUSTERED INDEX [UK_FUNCAO_FUNCAO] ON [nodetest].[FUNCAO]
(
	[FUNCAO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [UK_USUARIO_CPF] ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[nodetest].[USUARIO]') AND name = N'UK_USUARIO_CPF')
CREATE UNIQUE NONCLUSTERED INDEX [UK_USUARIO_CPF] ON [nodetest].[USUARIO]
(
	[CPF] ASC
)
WHERE ([DELETADO] IS NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

/****** Object:  Index [UK_USUARIO_EMAIL] ******/
IF NOT EXISTS (SELECT * FROM sys.indexes WHERE object_id = OBJECT_ID(N'[nodetest].[USUARIO]') AND name = N'UK_USUARIO_EMAIL')
CREATE UNIQUE NONCLUSTERED INDEX [UK_USUARIO_EMAIL] ON [nodetest].[USUARIO]
(
	[EMAIL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, IGNORE_DUP_KEY = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO
