version: "3.8"

services:
  web:
    build:
      context: ./
      dockerfile: ./Dockerfile
    image: ${DOCKER_WEB_IMAGE_NAME}
    container_name: ${DOCKER_WEB_CONTAINER_NAME}
    ports:
      - "80:4000"
      - "443:5000"
      - "5001:5001"
    volumes:
      - ${DOCKER_WEB_VOLUME_MOUNT}/logs:/home/node/app/logs
      - ${DOCKER_WEB_VOLUME_MOUNT}/queue:/home/node/app/queue
      - ${DOCKER_WEB_VOLUME_MOUNT}/sessions:/home/node/app/sessions
      - ${DOCKER_WEB_VOLUME_MOUNT}/uploads:/home/node/app/uploads
    restart: always
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    container_name: mssql
    ports:
      - "1433:1433"
    environment:
      - ACCEPT_EULA=Y
      - MSSQL_SA_PASSWORD=A12345678a
      - MSSQL_PID=Express
      - MSSQL_LCID=1046
      - MSSQL_COLLATION=Latin1_General_CI_AI
      - MSSQL_TCP_PORT=1433
      - TZ=America/Sao_Paulo
      - MSSQL_BACKUP_DIR=/var/backups
      - MSSQL_DATA_DIR=/var/opt/mssql/data/user
      - MSSQL_LOG_DIR=/var/opt/mssql/data/user
      - MSSQL_AGENT_ENABLED=false
    volumes:
      - ${DOCKER_DB_VOLUME_MOUNT}/data:/var/opt/mssql/data
      - ${DOCKER_DB_VOLUME_MOUNT}/log:/var/opt/mssql/log
      - ${DOCKER_DB_VOLUME_MOUNT}/secrets:/var/opt/mssql/secrets
      - ${DOCKER_DB_VOLUME_MOUNT}/backups:/var/backups
